### ISSUE TITLE
Onilne API is down

### ISSUE THREAD

**Issue by scemama** [mmottl/lacaml#41] opened 2018-05-28 16:50 UTC
Hello,
your online API is down:

http://mmottl.github.io/lacaml/api/lacaml

Error 404 Page not found

Best,
Anthony

**Comment by mmottl** [comment] 2018-05-28 22:31
Thanks for the report, the problem is now fixed.  This is the same issue as https://github.com/mmottl/sqlite3-ocaml/issues/30.

**Closed by mmottl** 2018-05-28 22:31 UTC

**Comment by scemama** [comment] 2018-05-29 12:05
Thank you for fixing this.
And thank you for Lacaml, which is VERY helpful!

**Comment by mmottl** [comment] 2018-05-29 12:34
Thanks for the feedback!
